[package]
name = "udp_listener"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1"
primitive = { git = "https://github.com/Banyc/primitive.git", tag = "v0.0.59" }
tokio = { version = "1", features = [
    "bytes",
    "io-util",
    "net",
    "sync",
    "time",
] }
tokio_udp = { git = "https://github.com/Banyc/tokio_udp.git", tag = "v0.0.3" }
tracing = "0.1"

[dev-dependencies]
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
